name: workflow-dispatch
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'set name'
        required: true
        default: 'github-actions'
        type: string
      environment:
        description: 'set env'
        required: false
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod